### ISSUE TITLE
BUG: Voeg een nieuwe versie toe van document

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1311]
***Steps to reproduce:***

(Zorg dat je alle rechten in keycloack hebt)
1. Maak een document aan en zet deze niet op definitief
2. voeg een nieuwe versie toe
3. 

***Expected***
wordt nieuwe versie toegevoegd

***Actual***
Krijg een 500

net.atos.zac.policy.exception.PolicyException
	at deployment.ROOT.war//net.atos.zac.policy.PolicyService.assertActie(PolicyService.java:161)
	at deployment.ROOT.war//net.atos.zac.app.informatieobjecten.InformatieObjectenRESTService.updateEnkelvoudigInformatieobject(InformatieObjectenRESTService.java:327)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Comment by robertverboom** [comment]
Test ok
