### ISSUE TITLE
BUG: Eerste keer inloggen geeft Forbidden en vervolgens BadRequest melding

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#1444]
***Steps to reproduce:***

1. Ga naar een omgeving
2. log in
3. 

***Expected***
gaat naar het zac beginscherm

***Actual***
Je gaat naar forbidden pagina. Na herladen krijg je een bad request pagina

**Comment by hansmarks** [comment]
Fout:


https://keycloak.develop-public-service-platform.net/auth/realms/develop/broker/google/login
 ?client_id=zaakafhandelcomponent
 &tab_id=4qUzHrs86d0
 &session_code=H2n9G8Ak-8CZDJOQf58PQOrxJlnUnvmh1CeRZ843a-0

HTTP 303

https://accounts.google.com/o/oauth2/v2/auth
 ?scope=openid+profile+email
 &state=X7cuz_Cj00TdaeiIVh7svfJIKvbl70YAbArm5pPNY0I.4qUzHrs86d0.zaakafhandelcomponent
 &response_type=code
 &client_id=1070914290251-aqjff9i3v724rfkbvcerf7isibqa50gr.apps.googleusercontent.com
 &redirect_uri=https://keycloak.develop-public-service-platform.net/auth/realms/develop/broker/google/endpoint&nonce=U400QaIG_bbYzI2BuGbopw

HTTP 302

https://keycloak.develop-public-service-platform.net/auth/realms/develop/broker/google/endpoint
 ?state=X7cuz_Cj00TdaeiIVh7svfJIKvbl70YAbArm5pPNY0I.4qUzHrs86d0.zaakafhandelcomponent
 &code=4/0ARtbsJqTbV-ODTvT-e9_ETAQDSw9NFEBpuKd9Q05WQbNYH-TCpw2HiX7qUqp82ch_2mN8w
 &scope=email+profile+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/userinfo.email+openid
 &authuser=0
 &hd=atos.net
 &prompt=none

HTTP 302

**https://zac.develop-public-service-platform.net/
 ?state=5ed60e39-e19e-4d9a-8d41-c67771a647fc
 &session_state=b6bbd2ff-2c0b-455b-9825-22206d0b2f70
 &code=931a8505-c132-4b4a-b4ac-94e1b72a019a.b6bbd2ff-2c0b-455b-9825-22206d0b2f70.b6b22337-6844-449d-9fad-9f993493ee0a**

REQUEST

:authority: zac.develop-public-service-platform.net
:method: GET
:path: /?state=5ed60e39-e19e-4d9a-8d41-c67771a647fc&session_state=b6bbd2ff-2c0b-455b-9825-22206d0b2f70&code=931a8505-c132-4b4a-b4ac-94e1b72a019a.b6bbd2ff-2c0b-455b-9825-22206d0b2f70.b6b22337-6844-449d-9fad-9f993493ee0a
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: nl,en-US;q=0.9,en;q=0.8
cookie: GCP_IAP_UID=112429262848638972715; GCP_IAP_XSRF_NONCE_Ui2frvMc1AHFxDUBGkNnWA=1; GCP_IAAP_AUTH_TOKEN_414DDCBFFAA046C8=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIwOWMwNTdkM2JkZDhjMDhmMmQ1NzM5Nzg4NjMyNjczZjdjNjI0MGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDcwOTE0MjkwMjUxLXQ0dmVybHA0bmtkMWgycnIydmducmI0b2tna2RpMnYyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA3MDkxNDI5MDI1MS10NHZlcmxwNG5rZDFoMnJyMnZnbnJiNG9rZ2tkaTJ2Mi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMjQyOTI2Mjg0ODYzODk3MjcxNSIsImhkIjoiYXRvcy5uZXQiLCJlbWFpbCI6ImhhbnMubWFya3NAYXRvcy5uZXQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6Ik1VVnU5WlE5TjVvZnpsR28wWVJiTFEiLCJnb29nbGUiOnsiZ2ljIjoiQU52YnZqLUNQZ2E1MlRHaGk4TEZIODEtM0NhcWZ0eHUtV2xiQXJyLTdkRmRDdTBhSlo2MG9nQVRfclRmTV9SWnZsMzdOT0FLcGpFVDhYQ0Nrd0xmeUhpUTdZbkx2em5nSUtqTWxxWi1WR2xCR20zUlNJLVl4bE10VC0xZzg3V3hqLTkwYVN6TXZERmExY0xmTXNMRHRZY3prZ0RmUHFRUWFXRm1JSmRlS1FmMjA2OGVJazVRSWRVOVY0YkF1WVBHRURLYlg4eUw0NzhoeHIzakliVkcyVm1mMHdxaUdvdHhzX2YtUlEifSwiaWF0IjoxNjYzOTMzMjEyLCJleHAiOjE2NjM5MzY4MTJ9.bc8eId5QDRCvKqc03ACVWkWHU9UfNLNVf_48SKEUer-oC2M3QMAhV91hzudgsUd2v7jjlSRsWHbhi3an8F29nHqBkyvHtXardQzqdmEY6MbArH9TFW1dhgpUlrgrvJvdLmWS7hm3w99AQOLIDu-xdnj2tIcMiSiKfhUqt8q9NGMZXMjc19cM_8Rx4WGkaDCEHSVxyme3AzD8wW3s7XoD8adTe9QxBWv3I69-rDPD5kNiWqSlQAg8fsetr5HWPYbGBxYNISnEnWBYqMxN1XuzDkQLM-wUbqXC9im2L-O_0KMnQLeA1876Tpijaqf48ltWOFYXOySRzrfIX2e7fRdAjg; OAuth_Token_Request_State=5ed60e39-e19e-4d9a-8d41-c67771a647fc
sec-ch-ua: "Chromium";v="105", "Not)A;Brand";v="8"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: cross-site
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.

RESPONSE

**HTTP 403**

alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-length: 68
content-type: text/html;charset=UTF-8
date: Fri, 23 Sep 2022 11:40:15 GMT
expires: 0
pragma: no-cache
set-cookie: OAuth_Token_Request_State=""; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:00 GMT
via: 1.1 google

**Comment by hansmarks** [comment]
Wat behalve het ontbreken van de Java-sessie ook opvalt is dat er bij de goede 2 GCP_IAP_XSRF_NONCE_'s in de cookies zitten en bij de foute maar 1.

**Comment by hansmarks** [comment]
Ik denk dat dit de bijbehorende foutmeldingen zijn in de keycloak server log (log heeft alleen relatieve timestamps):
- [0m[33m08:58:13,349 WARN  [org.keycloak.events] (default task-325) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=haven, clientId=null, userId=null, ipAddress=130.211.2.128, error=invalid_code, identity_provider=google

In de keycloak server log staan ook wat andere foutmeldingen waar misschien iets mee moet gebeuren, maar ik kan ze niet direct hieraan relateren (ook al omdat die log geen timestamps heeft):
-

En nog de nodige errors rondom het synchroniseren van groepen (email veld).

**Comment by hansmarks** [comment]
In de server log van de ZAC gebeurt er dit:

- INFO  [net.atos.zac.authentication.UserPrincipalFilter] (default task-16) User logged in: 'hans.marks@atos.net' with roles: [default-roles-haven, zaakafhandelcomponent_user, zaakbehandelaar, beheerder, uma_authorization, offline_access, recordmanager, werkverdeler]
- ERROR [org.wildfly.security.http.oidc] (default task-15) failed to turn code into token: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.httpcomponents.core//org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.httpcomponents.core//org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.httpcomponents.core//org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.httpcomponents.core//org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.httpcomponents.core//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.httpcomponents.core//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.httpcomponents.core//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.httpcomponents.core//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:131)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcRequestAuthenticator.resolveCode(OidcRequestAuthenticator.java:337)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcRequestAuthenticator.authenticate(OidcRequestAuthenticator.java:284)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.RequestAuthenticator.doAuthenticate(RequestAuthenticator.java:91)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.RequestAuthenticator.authenticate(RequestAuthenticator.java:44)
	at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcAuthenticationMechanism.evaluateRequest(OidcAuthenticationMechanism.java:82)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.auth.server.SecurityIdentityServerMechanismFactory$1.evaluateRequest(SecurityIdentityServerMechanismFactory.java:85)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.authenticate(HttpAuthenticator.java:325)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.access$800(HttpAuthenticator.java:300)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator.authenticate(HttpAuthenticator.java:94)
	at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.SecurityContextImpl.authenticate(SecurityContextImpl.java:107)
	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.ServletSecurityContextImpl.authenticate(ServletSecurityContextImpl.java:115)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
	at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
	at io.undertow.core@2.2.14.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.5.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)

**Comment by hansmarks** [comment]
11:26:36,594 ERROR [org.wildfly.security.http.oidc] (default task-59) failed to turn code into token: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
        at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
        at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcomponents.core//org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.httpcomponents.core//org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcomponents.core//org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.httpcomponents.core//org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.httpcomponents.core//org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.httpcomponents.core//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.httpcomponents.core//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.httpcomponents.core//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:131)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcRequestAuthenticator.resolveCode(OidcRequestAuthenticator.java:337)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcRequestAuthenticator.authenticate(OidcRequestAuthenticator.java:284)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.RequestAuthenticator.doAuthenticate(RequestAuthenticator.java:91)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.RequestAuthenticator.authenticate(RequestAuthenticator.java:44)
        at org.wildfly.security.elytron-http-oidc@1.18.3.Final//org.wildfly.security.http.oidc.OidcAuthenticationMechanism.evaluateRequest(OidcAuthenticationMechanism.java:82)
        at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.auth.server.SecurityIdentityServerMechanismFactory$1.evaluateRequest(SecurityIdentityServerMechanismFactory.java:85)
        at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.authenticate(HttpAuthenticator.java:325)
        at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator$AuthenticationExchange.access$800(HttpAuthenticator.java:300)
        at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.http.HttpAuthenticator.authenticate(HttpAuthenticator.java:94)
        at org.wildfly.security.elytron-web.undertow-server@1.10.1.Final//org.wildfly.elytron.web.undertow.server.SecurityContextImpl.authenticate(SecurityContextImpl.java:107)
        at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.ServletSecurityContextImpl.authenticate(ServletSecurityContextImpl.java:115)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:55)
        at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.core@2.2.14.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at org.wildfly.security.elytron-web.undertow-server-servlet@1.10.1.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
        at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.core@2.2.14.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow@26.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
        at io.undertow.servlet@2.2.14.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
        at io.undertow.core@2.2.14.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
        at io.undertow.core@2.2.14.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at org.jboss.xnio@3.8.5.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by hansmarks** [comment]
Wat me opvalt is die ServletInitialHandler.handleFirstRequest

Het lijkt alsof de/een servlet handler om een of andere reden niet meer actief was.

**Comment by hansmarks** [comment]
16:33:15,896 WARN  [org.wildfly.security.http.oidc] (default task-98) No state cookie
16:33:16,186 INFO  [net.atos.zac.authentication.UserPrincipalFilter] (default task-98) doFilter session 3aLxnGQEgKN75xRDGkOUAP_lzoUPjbifv6Hq8_2K user null
16:33:16,186 INFO  [net.atos.zac.authentication.UserPrincipalFilter] (default task-98) doFilter.setLoggedInUser session 3aLxnGQEgKN75xRDGkOUAP_lzoUPjbifv6Hq8_2K user hans.marks@atos.net
16:33:16,187 INFO  [net.atos.zac.authentication.UserPrincipalFilter] (default task-98) User logged in: 'hans.marks@atos.net' with roles: [zaakbehandelaar, zaakafhandelcomponent_user, default-roles-haven, werkverdeler, recordmanager, offline_access, uma_authorization, beheerder]

**Comment by andyverberne** [comment]
Wildfly en wat andere componenten zijn ge-upgrade. Ronnie heeft ook nog wat aanpassingen gedaan die een (positieve) invloed kunnen hebben. Voorlopig laten we deze even liggen.

**Comment by RoyBuis** [comment]
### Refinement KM, RV & RB

Dit kan op de huidige omgeving bij Atos niet opgelost worden. later opnieuw beoordelen op klantomgeving
