### ISSUE TITLE
BUG: 500 Error bij aanmaken zaak van zaaktype melding klein evenement op de Testomgeving van ZAC

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#1981]
***Steps to reproduce:***

1. Selecteer het zaaktype melding klein evenement
2. Maak een nieuwe zaak aan
3. 

***Expected***
Zaak wordt aangemaakt van het zaaktype melding klein evenement

***Actual***
Algemene Foutpagina

-- Gedeelte van de stacktrace ---
java.lang.NullPointerException: amountToAdd
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at java.base/java.time.LocalDate.plus(Unknown Source)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService.calculateDoorlooptijden(ZGWApiService.java:284)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService.createZaak(ZGWApiService.java:75)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService$Proxy$_$$_WeldClientProxy.createZaak(Unknown Source)
	at deployment.ROOT.war//net.atos.zac.app.zaken.ZakenRESTService.createZaak(ZakenRESTService.java:319)
	at jdk.internal.reflect.GeneratedMethodAccessor403.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

**Comment by nl23727** [comment]
Top, werkt weer prima.
