### ISSUE TITLE
BUG: Toevoegen van een document bij de Taak: Aanvullende informatie geeft een 500 error

### ISSUE THREAD

**Issue by nl23727** [NL-AMS-LOCGOV/zaakafhandelcomponent#2030]
***Steps to reproduce:***

1. Op de Test/Zandbak en Acceptatie omgeving speelt dit issue
2. Maak een nieuwe zaak aan
3. Maak een taak Aanvullende informatie aan
4. Open de taak Aanvullende informatie
5. Klik op de actie Document toevoegen
6. Vul de verplichte velden in en voeg het document toe aan de taak

***Expected***
Document wordt toegevoegd aan de Taak

***Actual***
Error 500 wordt getoond

Deel van de stacktrace: 
Cannot read field "file" because "bestand" is null
java.lang.NullPointerException: Cannot read field "file" because "bestand" is null
	at deployment.ROOT.war//net.atos.zac.app.informatieobjecten.converter.RESTInformatieobjectConverter.convertTaakObject(RESTInformatieobjectConverter.java:193)
	at deployment.ROOT.war//net.atos.zac.app.informatieobjecten.InformatieObjectenRESTService.createEnkelvoudigInformatieobject(InformatieObjectenRESTService.java:241)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.resteasy.resteasy-core@4.7.7.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)

**Comment by RoyBuis** [comment]
### Refinement 20-12

Code doorlopen op gebruik van uuid's als taak id. Dat moet een string zijn.
