### ISSUE TITLE
BUG: Bij aanmaken zaak treed een exceptie op

### ISSUE THREAD

**Issue by andyverberne** [NL-AMS-LOCGOV/zaakafhandelcomponent#618]
***Steps to reproduce:***

1. Maak een nieuwe zaak aan 
2. Kijk in de log

***Actual***

`[0m[31m09:23:58,808 ERROR [org.flowable.common.engine.impl.interceptor.CommandContext] (Weld Thread Pool -- 1) Error while closing command context: java.lang.NullPointerException: Cannot invoke "net.atos.zac.authentication.Medewerker.getGebruikersnaam()" because the return value of "javax.enterprise.inject.Instance.get()" is null
	at deployment.ROOT.war//net.atos.client.zgw.shared.util.ZGWClientHeadersFactory.removeMedewerkerToelichting(ZGWClientHeadersFactory.java:63)
	at deployment.ROOT.war//net.atos.client.zgw.zrc.ZRCClientService.createStatus(ZRCClientService.java:393)
	at deployment.ROOT.war//net.atos.client.zgw.zrc.ZRCClientService$Proxy$_$$_WeldSubclass.createStatus(Unknown Source)
	at deployment.ROOT.war//net.atos.client.zgw.zrc.ZRCClientService$Proxy$_$$_WeldClientProxy.createStatus(Unknown Source)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService.createStatusForZaak(ZGWApiService.java:227)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService.createStatusForZaak(ZGWApiService.java:101)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService$Proxy$_$$_WeldSubclass.createStatusForZaak(Unknown Source)
	at deployment.ROOT.war//net.atos.client.zgw.shared.ZGWApiService$Proxy$_$$_WeldClientProxy.createStatusForZaak(Unknown Source)
	at deployment.ROOT.war//net.atos.zac.flowable.cmmn.UpdateZaakLifecycleListener.updateZaak(UpdateZaakLifecycleListener.java:104)
	at deployment.ROOT.war//net.atos.zac.flowable.cmmn.UpdateZaakLifecycleListener.stateChanged(UpdateZaakLifecycleListener.java:87)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.listener.CmmnListenerNotificationHelper.executeLifecycleListener(CmmnListenerNotificationHelper.java:149)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.listener.CmmnListenerNotificationHelper.executeListeners(CmmnListenerNotificationHelper.java:140)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.listener.CmmnListenerNotificationHelper.executeLifecycleListeners(CmmnListenerNotificationHelper.java:129)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.agenda.operation.AbstractChangePlanItemInstanceStateOperation.run(AbstractChangePlanItemInstanceStateOperation.java:57)
	at deployment.ROOT.war//org.flowable.common.engine.impl.AbstractEngineConfiguration.lambda$new$0(AbstractEngineConfiguration.java:195)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.executeOperation(CmmnCommandInvoker.java:88)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.executeOperations(CmmnCommandInvoker.java:75)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.execute(CmmnCommandInvoker.java:64)
	at deployment.ROOT.war//org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at deployment.ROOT.war//org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:98)
	at deployment.ROOT.war//org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at deployment.ROOT.war//org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at deployment.ROOT.war//org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.runtime.CmmnRuntimeServiceImpl.startCaseInstance(CmmnRuntimeServiceImpl.java:101)
	at deployment.ROOT.war//org.flowable.cmmn.engine.impl.runtime.CaseInstanceBuilderImpl.start(CaseInstanceBuilderImpl.java:195)
	at deployment.ROOT.war//net.atos.zac.flowable.FlowableService.startCase(FlowableService.java:174)
	at deployment.ROOT.war//net.atos.zac.flowable.FlowableService$Proxy$_$$_WeldSubclass.startCase$$super(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:197)
	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:185)
	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:53)
	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:90)
	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:47)
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at deployment.ROOT.war//net.atos.zac.flowable.FlowableService$Proxy$_$$_WeldSubclass.startCase(Unknown Source)
	at deployment.ROOT.war//net.atos.zac.flowable.FlowableService$Proxy$_$$_WeldClientProxy.startCase(Unknown Source)
	at deployment.ROOT.war//net.atos.zac.flowable.cmmn.event.CmmnEventObserver.startZaakAfhandeling(CmmnEventObserver.java:64)
	at deployment.ROOT.war//net.atos.zac.flowable.cmmn.event.CmmnEventObserver.onFire(CmmnEventObserver.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.api//javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverNotifier.notifyAsyncObserver(ObserverNotifier.java:415)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverNotifier.lambda$notifyAsyncObservers$5(ObserverNotifier.java:358)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverNotifier.lambda$createSupplier$8(ObserverNotifier.java:442)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.auth.server.SecurityIdentity.runAsConsumer(SecurityIdentity.java:376)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.auth.server.Scoped.runAsConsumer(Scoped.java:112)
	at org.wildfly.security.elytron-base@1.18.3.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:60)
	at org.jboss.as.weld@26.0.1.Final//org.jboss.as.weld.services.bootstrap.WeldSecurityServices.lambda$getSecurityContextAssociator$1(WeldSecurityServices.java:106)
	at org.jboss.weld.core@3.1.8.Final//org.jboss.weld.event.ObserverNotifier.lambda$createSupplier$9(ObserverNotifier.java:438)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at org.jboss.as.weld@26.0.1.Final//org.jboss.as.weld.services.bootstrap.WeldExecutorServices$WeldTaskWrapper.run(WeldExecutorServices.java:170)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
`

**Comment by robertverboom** [comment]
test ok
