### ISSUE TITLE
communicatiekanaal kunnen bewerken op de zaakgegevenspagina

### ISSUE THREAD

**Issue by robertverboom** [NL-AMS-LOCGOV/zaakafhandelcomponent#722]
***Als*** behandelaar

***Wil ik*** een communicatiekanaal kunnen wijzigen op de zaakgegevenspagina

***Zodat*** van kanaal kan veranderen omdat ik bijvoorbeeld een fout gemaakt heb

***

### Acceptance criteria:
- inbewerk component bij kanaal
- naamgeving van kanaal moet communicatiekanaal worden. Zo wordt het ook in de VNG-referentielijsten genoemd

***
### Prioriteit
*Verwijder wat niet van toepassing is:*
- Must haves

***
### Gerealiseerd
_Omschrijving van de op te leveren functionaliteit in deze story_

***Belangrijkste functionaliteiten:***
- 
-

**Comment by robertverboom** [comment]
test ok

**Comment by robertverboom** [comment]
Test nok:
Communicatiekanaal dat niet gevuld is en wilt bewerken in zaakgegevenspagina geeft 500: 
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(Unknown Source)
	at java.base/java.util.UUID.fromString(Unknown Source)

**Comment by robertverboom** [comment]
test ok

**Comment by VictorTielenius** [comment]
Communicatiekanaal kunnen wijzigen op de zaakgegevenspagina.
Dit moet bij Historie komen te staan:
OK
